# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Dangle' do
pod 'CocoaLumberjack'
pod 'LayerKit'
pod 'SVProgressHUD', :head
pod 'ClusterPrePermissions', '~> 0.1'
pod 'JSQSystemSoundPlayer', '~> 2.0'
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'

end
